name: Build and Release

on:
  workflow_dispatch:
    branches: [ main ]
    inputs:
      release_name:
        description: "Name for release (e.g. Release v1.x)"
        required: true
      tag:
        description: 'Tag for release (e.g. v1.x.x)'
        required: true
      prerelease:
        description: 'Is this a prerelease?'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew build

      - name: Find main JAR
        id: find_jar
        run: |
          MAIN_JAR=$(ls build/libs/*.jar | grep -vE '(-sources|-javadoc)\.jar$' | head -n 1)
          echo "jar=$MAIN_JAR" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.release_name }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}
          files: ${{ steps.find_jar.outputs.jar }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}